# Use official NGINX base image
FROM nginx:1.25.0

# Remove default nginx.conf to use custom one
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom nginx.conf and SSL certificates
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./certs /etc/nginx/certs

# Expose port 443 for HTTPS
EXPOSE 443
